# Generated by Django 4.0.4 on 2022-05-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Admn', models.CharField(max_length=40)),
                ('Faculty', models.CharField(choices=[('1', 'School of Science'), ('2', 'School of Engineering'), ('3', 'School of Art'), ('4', 'School of Infocoms'), ('5', 'School of Business')], max_length=200)),
                ('Course', models.CharField(max_length=50)),
                ('id_No', models.IntegerField()),
            ],
        ),
    ]
