# Generated by Django 4.0.4 on 2022-05-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_No',
        ),
    ]
