# Generated by Django 4.0.6 on 2022-10-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_student_course_remove_student_id_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('admn_no', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('faculty', models.CharField(choices=[('1', 'School of Space Science'), ('2', 'School of Engineering'), ('3', 'School of Art'), ('4', 'School of Infocoms'), ('5', 'School of Business'), ('6', 'School of Aeronautical Engineering'), ('7', 'School of Meadicine')], max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
