# Generated by Django 4.0 on 2022-10-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_studentdetails_delete_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdetails',
            options={'verbose_name_plural': 'Student Details'},
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='faculty',
            field=models.CharField(choices=[('1', 'School of Space Science'), ('2', 'School of Engineering'), ('3', 'School of Art'), ('4', 'School of Infocoms'), ('5', 'School of Business'), ('6', 'School of Aeronautical Engineering'), ('7', 'School of Medicine')], max_length=200),
        ),
    ]
