# Generated by Django 4.0 on 2022-10-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_studentdetails_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'BSc in Physics with Astro-Physics'), (2, 'BS in Astrobiology'), (3, 'Bachelor of Science in Astronomy and Astrophysics'), (4, 'BSc (Hons) in Physics and Astrophysics'), (5, 'BS in Astronomy'), (6, 'Bachelor of Science in Astronomy'), (7, 'Bachelor of Arts in Earth & Space Sciences.')], max_length=200)),
            ],
            options={
                'verbose_name_plural': 'School Programs',
            },
        ),
    ]
