# Generated by Django 4.0 on 2022-10-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_schoolprograms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprograms',
            name='name',
            field=models.CharField(choices=[('School of Space Science', (('1', 'BSc in Physics with Astro-Physics'), ('2', 'BS in Astrobiology'), ('3', 'Bachelor of Science in Astronomy and Astrophysics'), ('4', 'BSc (Hons) in Physics and Astrophysics'), ('5', 'BS in Astronomy'), ('6', 'Bachelor of Science in Astronomy'), ('7', 'Bachelor of Arts in Earth & Space Sciences.')))], max_length=200),
        ),
    ]
