# Generated by Django 4.0 on 2022-10-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_schoolprograms_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='faculty',
            field=models.CharField(choices=[('1', 'School of Space Science'), ('2', 'School of Engineering'), ('3', 'School of Art'), ('4', 'School of Infocoms'), ('5', 'School of Business'), ('6', 'School of Medicine')], default='Science', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='course',
            field=models.CharField(choices=[('School of Space Science', ((1, 'BSc in Physics with Astro-Physics'), (2, 'BS in Astrobiology'), (3, 'Bachelor of Science in Astronomy and Astrophysics'), (4, 'BSc (Hons) in Physics and Astrophysics'), (5, 'BS in Astronomy'), (6, 'Bachelor of Science in Astronomy'), (7, 'Bachelor of Arts in Earth & Space Sciences.'))), ('School of Engineering', ((1, 'BSc in Electrical engineering'), (2, 'BSc in Civil Engineering'), (3, 'Bsc Chemical Engineering'), (4, 'BSc in Environmental engineering'), (5, 'BSc in Aeronautical Engineering'), (6, 'BSc in Automobile Engineering'), (7, 'Bsc Biomedical engineering'))), ('School of Infocoms', ((1, 'BSc in Information technology'), (2, 'BSc in IT and Media Studies'), (3, 'Bsc Chemical Engineering'), (4, 'BSc in Environmental engineering'), (5, 'BSc in Aeronautical Engineering'), (6, 'BSc in Automobile Engineering'), (7, 'Bsc Biomedical engineering'))), ('School of Art', ((1, 'Bachelor of Arts (Kiswahili)'), (2, 'Bachelor of Arts (English)'), (3, 'Bachelor of Arts (German)'), (4, 'Bachelor of Arts (French)'))), ('School of Business', ((1, 'Bachelor of Accounting and Finance'), (2, 'Bachelor of Business Administration and Entreprenuership'), (3, 'Bachelor of Management Science and Technology)'), (4, 'Bachelor of Economics And Resource Management'))), ('School of Medicine', ((1, 'Department of Human Anatomy'), (2, 'Bachelors of Pathology'), (3, 'Bachelor of Medical Microbiology & Parasitology.)'), (4, 'Bachelor of Paediatrics and Child Health'), (5, 'Bachelors of Psychiatry and Mental health.')))], default='CSC', max_length=200),
        ),
    ]
